<template>
  <v-container>
    <v-card>
      <v-card-title>
        Signup
      </v-card-title>
      <v-card-text>
        <v-form>
          <v-text-field
            v-model="name"
            :counter="10"
            label="name"
            required
          ></v-text-field>
          <v-text-field
            v-model="password"
            :counter="10"
            label="password"
            required
          ></v-text-field>
          <v-btn
            class="mr-4"
            @click="submit"
          >
            Signup
          </v-btn>
        </v-form>
      </v-card-text>
    </v-card>
  </v-container>
</template>